-- Auto-generated, parent-facing explanation of a session's confirmed wrong
-- answers (AI prose, no counts — see generate-parent-error-summary.ts).
-- Regenerated by confirmReviewAction every time a correction scan is
-- confirmed, and always stored on the root scan (the one ParentReportWorkspace
-- renders against), never on a correction scan itself.
alter table worksheet_scans
  add column parent_summary text;
